<?php

use Illuminate\Database\Seeder;

class ConcessionPeriodsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date_start = '2019-01-01';
        $date_end = '2019-07-07';

        $data = [
            [ 'id_rm_establishment_concession_period'=> 49,  'id_rm_period_concession_period' =>    3, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 49,	 'id_rm_period_concession_period' =>    2541, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 52,	 'id_rm_period_concession_period' =>    4, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 52,	 'id_rm_period_concession_period' => 	2524, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 70,  'id_rm_period_concession_period' => 	5, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 70,	 'id_rm_period_concession_period' => 	2539, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 74,  'id_rm_period_concession_period' => 	6, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 74,  'id_rm_period_concession_period' => 	2538, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 95,  'id_rm_period_concession_period' => 	7, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 95,  'id_rm_period_concession_period' => 	2537, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 99,  'id_rm_period_concession_period' => 	8, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 99,  'id_rm_period_concession_period' => 	2536, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 101, 'id_rm_period_concession_period' => 	9, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 101, 'id_rm_period_concession_period' => 	2535, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 102, 'id_rm_period_concession_period' => 	10, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 102, 'id_rm_period_concession_period' => 	2534, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 104, 'id_rm_period_concession_period' => 	11, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 138, 'id_rm_period_concession_period' =>	12, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 138, 'id_rm_period_concession_period' =>	2533, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 141, 'id_rm_period_concession_period' =>	13, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 141, 'id_rm_period_concession_period' =>	2532, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 142, 'id_rm_period_concession_period' =>    14, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 142, 'id_rm_period_concession_period' =>    2531, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 167, 'id_rm_period_concession_period' =>    15, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 167, 'id_rm_period_concession_period' => 	2530, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 168, 'id_rm_period_concession_period' => 	16, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 168, 'id_rm_period_concession_period' =>	2523, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2, 'id_rm_period_code_concession_period'    =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	22, 'id_rm_period_code_concession_period'   =>	'2019-11', 'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2396, 'id_rm_period_code_concession_period' =>	'2019-12', 'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2419, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2398, 'id_rm_period_code_concession_period' =>	'2019-21', 'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2399, 'id_rm_period_code_concession_period' =>	'2019-22', 'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2391, 'id_rm_period_code_concession_period' =>	'2019-A',  'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2392, 'id_rm_period_code_concession_period' =>	'2019-B',  'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2393, 'id_rm_period_code_concession_period' =>	'2019-C',  'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2418, 'id_rm_period_code_concession_period' =>	'2019-C-A','id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2394, 'id_rm_period_code_concession_period' =>	'2019-D',  'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 169, 'id_rm_period_concession_period' =>	2395, 'id_rm_period_code_concession_period' =>	'2019-E',  'id_rm_modality_concession_period' => 'D','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 171, 'id_rm_period_concession_period' =>    17, 'id_rm_period_code_concession_period'   => 	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 171, 'id_rm_period_concession_period' =>    2526, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 173, 'id_rm_period_concession_period' =>    18, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 173, 'id_rm_period_concession_period' =>    2527, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 174, 'id_rm_period_concession_period' =>    2410, 'id_rm_period_code_concession_period' =>	'2019-0',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 174, 'id_rm_period_concession_period' =>    19, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 174, 'id_rm_period_concession_period' =>    2528, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 187, 'id_rm_period_concession_period' =>    20, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 187, 'id_rm_period_concession_period' =>    2529, 'id_rm_period_code_concession_period' =>	'2019-2',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1],
            [ 'id_rm_establishment_concession_period'=> 191, 'id_rm_period_concession_period' =>    23, 'id_rm_period_code_concession_period'   =>	'2019-1',  'id_rm_modality_concession_period' => 'P','date_start_concession_period' => $date_start, 'date_end_concession_period' => $date_end, 'fk_user' => 1]

        ];

        DB::table('concession_periods')->insert($data);
        
    }
}
