<?php

use Illuminate\Database\Seeder;

class DiscountMarginSchoolarshipsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dados = array(
            
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 1, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 2, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 3, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 4, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 5, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 6, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 7, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 8, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 9, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 10, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 11, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 12, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 13, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 14, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 15, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 16, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 18, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 19, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 20, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 21, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 23, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 25, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP007', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 1, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 2, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 3, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 4, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 5, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 6, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 7, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 8, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 9, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 10, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 11, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 12, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 13, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 14, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 15, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 16, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 18, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 19, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 20, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 21, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 23, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1),
            array('id_rm_establishment_discount_margin_schoolarship' => 169, 'id_rm_schoolarship_discount_margin_schoolarship' => 25, 'id_rm_course_type_discount_margin_schoolarship' => 3, 'id_rm_modality_discount_margin_schoolarship' => 'P', 'id_rm_major_discount_margin_schoolarship' => 'GP011', 'id_rm_period_discount_margin_schoolarship' => 20, 'id_rm_period_code_discount_margin_schoolarship' => '2019-1', 'max_value_discount_margin_schoolarship' => 30, 'is_exact_value_discount_margin_schoolarship' => false, 'fk_user' => 1)
        );
        echo 'Migrando dados';
        DB::table('discount_margin_schoolarships')->insert($dados);
    }
}
